Update pipline

diff --git a/.github/workflows/terraform-feature.yml b/.github/workflows/terraform-feature.yml
--- a/.github/workflows/terraform-feature.yml
+++ b/.github/workflows/terraform-feature.yml
@@ -49,8 +49,16 @@ jobs:
     ls -la
     echo "Terraform files:"
     find . -maxdepth 2 -type f -print
+    
+    - name: Check tfvars
+  run: |
+    pwd
+    ls -la
+    ls -la Enviroment/prod
+    test -f Enviroment/prod/terraform.tfvars && echo "TFVARS FOUND" || echo "TFVARS NOT FOUND"
 
       - name: Terraform Plan
+  working-directory: ./Enviroment/prod
   run: terraform plan -input=false -var-file="./terraform.tfvars"
 
       - name: Terraform Security Scan
